Add director
spankyntosh/java-filmorate pull request #14
Opened 2023-03-20 17:28 UTC by spankyntosh

2023-03-20 19:16 UTC, aydarhub requested changes
Оставил некоторые комментарии. Основное - это лучше избавиться от запросов в цикле. Тут на хабре кто-то сравнивал batchUpdate и цикл, batchUpdate сработал в 10 раз быстрее.
https://habr.com/ru/post/703828/

2023-03-20 19:16 UTC, aydarhub commented on src/main/resources/schema.sql
Нужно изменить порядок удаления таблиц (таблицы режиссеров не дают удалить таблицу фильмов), а лучше, как предлагал Алексей, заменить всё на 'DROP ALL OBJECTS'

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +import lombok.Value;
неиспользуемый импорт

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/service/DbDirectorService.java
> +        if (director.getName() == null || director.getName().isEmpty()) {
Для проверок на null лучше использовать `Objects.isNull()`. Не помню почему, но ревьюер Владимир Цюман мне оставлял замечания по этому поводу.

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDAO.java
> +    Director addDirectorInfo(Director director);
тут скорее придираюсь, но я бы убрал слово "Info" из названий методов, чтобы было короче, смысл не потеряется.

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +        film.setDirectors(filmDirectorDAO.getFilmDirectors(filmId));
4 запроса в БД, чтобы получить фильм. Мне кажется, лучше переделать запрос получения фильма, используя JOIN. Не знаю, как к этому отнесется заказчик.

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                insertIntoFilmsDirectorsTable(filmId, director.getId());
запрос в цикле не стоит делать. Лучше использовать JdbcTemplate.batchUpdate(). Если нужно, могу скинуть пример использования у себя.

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                filmDirectorDAO.addRecord(director.getId(), film.getId());
тоже запрос в цикле

2023-03-20 19:16 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +            throw new QueryParamException(String.format("Допустимые значения для sortBy likes или year"));
тут String.format() ни к чему.

2023-03-20 19:47 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +            throw new QueryParamException(String.format("Допустимые значения для sortBy likes или year"));
сделал

2023-03-20 19:52 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +import lombok.Value;
сделал

2023-03-20 19:59 UTC, spankyntosh commented on src/main/resources/schema.sql
Переделал. Не стал заменять на DROP ALL OBJECTS. Так как это вызовет конфилкт при мердже

2023-03-20 20:03 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/service/DbDirectorService.java
> +        if (director.getName() == null || director.getName().isEmpty()) {
Сделал. Не понимаю чем лучше использовать Objects.isNull() так как его реализация такая
  public static boolean isNull(Object obj) {
        return obj == null;
    }

2023-03-20 20:05 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/DirectorDAO.java
> +    Director addDirectorInfo(Director director);
Не стал менять

2023-03-20 20:58 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                filmDirectorDAO.addRecord(director.getId(), film.getId());
Сделал

2023-03-20 21:08 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                insertIntoFilmsDirectorsTable(filmId, director.getId());
Сделал

2023-03-20 21:25 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +        film.setDirectors(filmDirectorDAO.getFilmDirectors(filmId));
В принципе согласен, но не стал менять так как потребует переделки во многих частях кода. Нет столько времени. Мою текущую реализацию принял тот же ревьюер, который будет проверять совместный проект. Думаю проблем не будет.

2023-03-21 06:12 UTC, aydarhub commented on src/main/resources/schema.sql
Чтобы удалить films нужно удалить сначала films_director.

2023-03-21 06:12 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/service/DbDirectorService.java
> +        if (director.getName() == null || director.getName().isEmpty()) {
да, почитал форумы, действительно разницы нет. Фактически, этот метод предназначен для использования в качестве предиката.

2023-03-21 06:25 UTC, aydarhub approved these changes

2023-03-21 06:31 UTC, merged