Добавление базы данных в качестве долговременного хранилища данных
spankyntosh/java-filmorate pull request #4
Opened 2023-03-05 21:28 UTC by spankyntosh

2023-03-06 22:54 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, отлично. 
После правки кода на основе комментариев и (или) принятия их к сведению ("Надо исправить" и "Можно лучше"), присылай работу на продолжение проверки.
Спасибо.

2023-03-06 22:54 UTC, zgreen3 commented on README.md
> +![](er%20diagram.png)
Отлично:
Отлично, что ты добавил схему БД в описание проекта, потому что файл README.md - это самое подходящее место для краткого описания основного функционала проекта, и/или технических деталей его работы и настроек, для других разработчиков, которые могут использовать его код.

2023-03-06 22:54 UTC, zgreen3 commented on pom.xml
> +			<version>2.1.212</version>
Можно по-другому:
Благодаря стартерам Spring Boot-а можно не указывать версии основных зависимостей в данном файле (драйвер БД H2 относится к таким зависимостям).
Также можно указать, что эта БД требуется только в рантайме, т.е.:
`<scope>runtime</scope>`

2023-03-06 22:54 UTC, zgreen3 commented on pom.xml
> +		<dependency>
Отлично:
Нужные зависимости по работе с БД добавлены в полном соответствии с ТЗ, отлично!

2023-03-06 22:54 UTC, zgreen3 commented on src/main/resources/application.properties
> +spring.datasource.password=userPassword
Отлично:
Вижу, что добавлены все нужные настройки для конфигурования базы данных H2 для рабочего режима, в полном соответствии с ТЗ, отлично!

2023-03-06 22:54 UTC, zgreen3 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS mpa_ratings (
Можно лучше:
Поскольку между таблицей фильмов и таблицей рейтингов имеется отношение многие к одному (т.к. много фильмов может относиться к одному рейтингу, но много рейтингов mpaa (исходя из имеющейся логики предметной области для этого рейтинга и предыдущих ТЗ)  не могут относится к одному фильму, другими словами, только один рейтинг может относиться к одному фильму), постольку можно упростить схему БД в этой части, исключив данную таблицу и внеся rating_id непосредственно в таблицу фильмов.

2023-03-06 22:54 UTC, zgreen3 commented on src/main/resources/data.sql
> +INSERT INTO mpa_ratings (name)
Отлично:
Вижу, что корректно добавлены скрипты `schema.sql`, `data.sql`, в полном соответствии с ТЗ, отлично!

2023-03-06 22:54 UTC, zgreen3 commented on src/test/java/ru/yandex/practicum/filmorate/AddFilmWithNegativeDurationTest.java
>  import org.junit.jupiter.api.Order;
Отлично:
Отлично, что ты так тщательно подошёл к тестированию функционала данного приложения!
При этом все юнит-тесты, связанные с методами одного класса обычно размещают в одном тестовом классе / одном файле с юнит-тестами, так немного упрощается структура тестов в сложных проектах.

2023-03-06 22:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +    public Collection<Film> getPopularFilms(Integer count) {
Можно лучше:
Этот метод не относится напрямую к CRUD-методам (другими словами, он составной, сложнее простых CRUD-операций), поэтому его лучше вынести на уровень сервисов.

2023-03-06 22:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +        String statement = "SELECT * "
Можно лучше:
Чтобы немного уменьшить работу для мэппера и исключить риск наличия двух одноимённых полей у разных соединяемых (join-ом) таблиц в процессе их мэппинга, можно написать `SELECT f.* ...`

2023-03-06 22:54 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                .peek(film -> film.setMpa(mpaFilmDAO.getMpaByFilmId(film.getId())))
Можно лучше:
Можно соединить таблицу фильмов с талицей mpa (через join), чтобы не отправлять множество запросов к БД в данной строке кода.

2023-03-08 19:36 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +                .peek(film -> film.setMpa(mpaFilmDAO.getMpaByFilmId(film.getId())))
> Можно лучше: Можно соединить таблицу фильмов с талицей mpa (через join), чтобы не отправлять множество запросов к БД в данной строке кода.

Чтобы не менять логику работы других методов из-за предложенных изменений в классе FilmMapper создал ещё один конструктор куда передаются mpaFilmDAO и filmGenreDAO для того чтобы при необходимости добавлять к фильму рейтинг и жанры.

2023-03-08 19:46 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +    public Collection<Film> getPopularFilms(Integer count) {
Сделал

2023-03-08 19:46 UTC, spankyntosh commented on src/main/java/ru/yandex/practicum/filmorate/dao/implementation/FilmDAOImpl.java
> +        String statement = "SELECT * "
сделал

2023-03-08 19:46 UTC, spankyntosh commented on pom.xml
> +			<version>2.1.212</version>
сделал

2023-03-08 19:48 UTC, spankyntosh commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS mpa_ratings (
Не стал реализовывать данное улучшение. Потребуется относительно много времени, а на текущей работе завал((

2023-03-09 06:33 UTC, zgreen3 approved these changes
Привет, вижу, что ты учёл все важные комментарии, отлично! 
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.

2023-03-11 15:03 UTC, merged