Add common films
spankyntosh/java-filmorate pull request #8
Opened 2023-03-15 21:37 UTC by kmmins

Задача по добавлению функциональности «Общие фильмы» выполнена.  Добавлен новый эндпоинт в FilmController, добавлена новая логика в DbFilmService.

2023-03-16 12:46 UTC, aydarhub requested changes, later dismissed

2023-03-16 12:46 UTC, aydarhub commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        return commonFilms;
Это лучше перенести в DAO класс

2023-03-17 09:56 UTC, kmmins commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        return commonFilms;
Перенес.

2023-03-17 17:44 UTC, spankyntosh approved these changes

2023-03-18 12:39 UTC, spankyntosh approved these changes

2023-03-18 12:41 UTC, merged